import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Offer from "./components/Offer";
import CustomHead from "./components/CustomHead";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Jezer Espinoza Painting LLC",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <link rel="icon" href="/logo.png" sizes="any" />
      <body className={inter.className}>
        <div className="">
          <Header/>
          <Offer/>
          {/* <Navbar/> */}
          <main>{children}</main>
          <Footer/>
        </div>
      </body>
    </html>
  );
}
